//
//  Settings.swift
//  Novee
//
//  Created by Nick on 2022-10-21.
//

import Foundation

struct Settings: Codable {
    var preferedLanguage: Language
}

enum Language: String, Codable, CaseIterable, Hashable {
    case AB = "Abkhazian",
         AA = "Afar",
         AF = "Afrikaans",
         AK = "Akan",
         SQ = "Albanian",
         AM = "Amharic",
         AR = "Arabic",
         AN = "Aragonese",
         HY = "Armenian",
         AS = "Assamese",
         AV = "Avaric",
         AE = "Avestan",
         AY = "Aymara",
         AZ = "Azerbaijani",
         BM = "Bambara",
         BA = "Bashkir",
         EU = "Basque",
         BE = "Belarusian",
         BN = "Bengali",
         BH = "Bihari languages",
         BI = "Bislama",
         BS = "Bosnian",
         BR = "Breton",
         BG = "Bulgarian",
         MY = "Burmese",
         CA = "Catalan",
         KM = "Central Khmer",
         CH = "Chamorro",
         CE = "Chechen",
         NY = "Chichewa",
         ZH = "Chinese",
         CU = "Old Bulgarian",
         CV = "Chuvash",
         KW = "Cornish",
         CO = "Corsican",
         CR = "Cree",
         HR = "Croatian",
         CS = "Czech",
         DA = "Danish",
         DV = "Divehi",
         NL = "Dutch",
         DZ = "Dzongkha",
         EN = "English",
         EO = "Esperanto",
         ET = "Estonian",
         EE = "Ewe",
         FO = "Faroese",
         FJ = "Fijian",
         FI = "Finnish",
         FR = "French",
         FF = "Fulah",
         GD = "Gaelic",
         GL = "Galician",
         LG = "Ganda",
         KA = "Georgian",
         DE = "German",
         KI = "Gikuyu",
         EL = "Greek (Modern)",
         KL = "Greenlandic",
         GN = "Guarani",
         GU = "Gujarati",
         HT = "Haitian",
         HA = "Hausa",
         HE = "Hebrew",
         HZ = "Herero",
         HI = "Hindi",
         HO = "Hiri Motu",
         HU = "Hungarian",
         IS = "Icelandic",
         IO = "Ido",
         IG = "Igbo",
         ID = "Indonesian",
         IA = "Interlingua (International Auxiliary Language Association)",
         IE = "Interlingue",
         IU = "Inuktitut",
         IK = "Inupiaq",
         GA = "Irish",
         IT = "Italian",
         JA = "Japanese",
         JV = "Javanese",
         KN = "Kannada",
         KR = "Kanuri",
         KS = "Kashmiri",
         KK = "Kazakh",
         RW = "Kinyarwanda",
         KV = "Komi",
         KG = "Kongo",
         KO = "Korean",
         KJ = "Kwanyama, Kuanyama",
         KU = "Kurdish",
         KY = "Kyrgyz",
         LO = "Lao",
         LA = "Latin",
         LV = "Latvian",
         LB = "Letzeburgesch, Luxembourgish",
         LI = "Limburgish, Limburgan, Limburger",
         LN = "Lingala",
         LT = "Lithuanian",
         LU = "Luba-Katanga",
         MK = "Macedonian",
         MG = "Malagasy",
         MS = "Malay",
         ML = "Malayalam",
         MT = "Maltese",
         GV = "Manx",
         MI = "Maori",
         MR = "Marathi",
         MH = "Marshallese",
         RO = "Moldovan, Moldavian, Romanian",
         MN = "Mongolian",
         NA = "Nauru",
         NV = "Navajo, Navaho",
         ND = "Northern Ndebele",
         NG = "Ndonga",
         NE = "Nepali",
         SE = "Northern Sami",
         NO = "Norwegian",
         NB = "Norwegian Bokmål",
         NN = "Norwegian Nynorsk",
         II = "Nuosu, Sichuan Yi",
         OC = "Occitan (post 1500)",
         OJ = "Ojibwa",
         OR = "Oriya",
         OM = "Oromo",
         OS = "Ossetian, Ossetic",
         PI = "Pali",
         PA = "Panjabi, Punjabi",
         PS = "Pashto, Pushto",
         FA = "Persian",
         PL = "Polish",
         PT = "Portuguese",
         QU = "Quechua",
         RM = "Romansh",
         RN = "Rundi",
         RU = "Russian",
         SM = "Samoan",
         SG = "Sango",
         SA = "Sanskrit",
         SC = "Sardinian",
         SR = "Serbian",
         SN = "Shona",
         SD = "Sindhi",
         SI = "Sinhala, Sinhalese",
         SK = "Slovak",
         SL = "Slovenian",
         SO = "Somali",
         ST = "Sotho, Southern",
         NR = "South Ndebele",
         ES = "Spanish, Castilian",
         SU = "Sundanese",
         SW = "Swahili",
         SS = "Swati",
         SV = "Swedish",
         TL = "Tagalog",
         TY = "Tahitian",
         TG = "Tajik",
         TA = "Tamil",
         TT = "Tatar",
         TE = "Telugu",
         TH = "Thai",
         BO = "Tibetan",
         TI = "Tigrinya",
         TO = "Tonga (Tonga Islands)",
         TS = "Tsonga",
         TN = "Tswana",
         TR = "Turkish",
         TK = "Turkmen",
         TW = "Twi",
         UG = "Uighur, Uyghur",
         UK = "Ukrainian",
         UR = "Urdu",
         UZ = "Uzbek",
         VE = "Venda",
         VI = "Vietnamese",
         VO = "Volap_k",
         WA = "Walloon",
         CY = "Welsh",
         FY = "Western Frisian",
         WO = "Wolof",
         XH = "Xhosa",
         YI = "Yiddish",
         YO = "Yoruba",
         ZA = "Zhuang, Chuang",
         ZU = "Zulu"
    
    static func getValue(_ value: String) -> String? {
        for language in Language.allCases {
            if "\(language)" == value {
                return language.rawValue
            }
        }
        
        return nil
    }
}
